language: node_js
node_js:
  - "stable"    # Node stable
  - "iojs"      # io.js latest
  - "unstable"  # Node unstable
  - "0.12"
  - "0.10"
  - "0.8"
  - "iojs-v1"

matrix:
  allow_failures:
    - node_js: "unstable"  # Node unstable
    - node_js: "iojs"      # io.js latest

install:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Update npm itself, if pre-version 2.x
  - if [[ "`npm --version`" =~ ^1\. ]]; then npm install -g npm@2.11; fi
  # Install with dependencies
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test
